spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/store
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
  application:
    name: platform.shared.notificationpromptmiddle
    version: 1.0.0
swagger:
  title: Jax-RS Course
  description: Creating RESTful Web Services with Jersey
  contact:
    name: Rafael de Pieri Barbosa
    url: http://www.alura.com
    email: rafaelpieribarbosa@gmail.com
  version: 0.0.1