spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/store
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update