spring:
  application:
      name: store
      version: 1.0.0
  datasource:
    url: jdbc:mysql://localhost:3306/storeDB?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update

swagger:
  title: Jax-RS Course
  description: Creating RESTful Web Services with Jersey.
  version: 0.0.1